buegufgauwfuewf
    dcAYGeyfgYAGYFG
    sa
    fs('dghkoijgfdsal;'
       ':kighdseriawae\rawe'
       'qfa'
       'wrga'
       'wreg'
       'er'
       'gq'
       'erq'
       'get'
       'h'
       's'
       's'
       'fd'
       'skelgserogwiergwer')